### ISSUE TITLE
[Meta] Feature Wishlist

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#6]
**Feature Wishlist:**
- [x] Refer Issue #5 
- [x] Refer Issue #7 
- [ ] Refer Issue #4 
- [ ] Extend the data flow analysis to improve optimisations and inference on the IR.
- [ ] Control Flow Restructuring.
- [ ] Control Flow Recovery.
- [ ] Emit C-code

**Comment by sushant94** [comment]
Opening individual issues to track.
